phpfastcache_v2.1_release/phpfastcache/phpfastcache.php
increment, decrement & touch methods issue has been solved
=> Solved Issue #62

phpfastcache/3.0.0/phpfastcache.php
=> replace eval for call_user_func_array

phpfastcache/3.0.0/abstract.php
=> #112 Warning: Illegal string offset 'value'

phpfastcache/3.0.0/drivers/files.php, phpfastcache/3.0.0/phpfastcache.php
=> Replaced all die calls to error throws

phpfastcache/3.0.0/abstract.php
=> 119 remove eval

phpfastcache/3.0.0/drivers/files.php, phpfastcache/3.0.0/drivers/sqlite.php, phpfastcache/3.0.0/phpfastcache.php
- Use realpath() to merge possible consecutive `//` inside path
- Improve info returned by driver_stats() for files driver
- Fix bug in driver_stats() for sqlite driver. indexing table would
reset the size
- Create 2 class constants in sqlite driver to improve readability
=> Improved driver_stats() for sqlite driver

phpfastcache/3.0.0/drivers/files.php
Before data property was empty now it contains array of all keys in cache with each holding array of size and write time.
=>  Improved stats function for files driver

phpfastcache/3.0.0/drivers/files.php
Reverts khoaofgod/phpfastcache#150
=> Revert " Improved stats function for files driver"

phpfastcache/3.0.0/drivers/memcached.php
see:
http://php.net/manual/en/memcached.add.php
http://php.net/manual/en/memcached.expiration.php
added if() similar to memcache.php
fixes #167
=> fixed expiration time

.codeclimate.yml
- Disabled UnusedFormalParameter due to interface implementations
- Disabled Controversial/CamelCaseClassName due to driver name implementations
=> Improved codeclimate configuration:

examples/Search.YourCaching.php, src/phpFastCache/Core/DriverAbstract.php
https://github.com/PHPSocialNetwork/phpfastcache/issues/267
=> Fix Tags & Search

examples/phpinfo.php, src/phpFastCache/CacheManager.php
I fixed a typo and added a missing closing tag.
=> Minor fixes

src/phpFastCache/Core/phpFastCache.php, src/phpFastCache/Drivers/memcache.php
- Added config field: compress_data
- If compress_data is set, enabled compression in Memcache driver
=> Added compression support for Memcache driver

src/phpFastCache/CacheManager.php
=> Fixed and simplified the clearing of the instance array.

.travis.yml, README.md, src/phpFastCache/Api.php, src/phpFastCache/Cache/ExtendedCacheItemPoolInterface.php, src/phpFastCache/Core/ExtendedCacheItemPoolTrait.php, src/phpFastCache/Core/StandardPsr6StructureTrait.php, tests/AttachingDetachingMethods.test.php
+ Added tests
(cherry picked from commit 1e22514)
=>  Implemented #331

.gitignore, composer.json, composer.lock
(cherry picked from commit 09672b3e7f0759c7e4ea2c0f8f04e1e6372aea26)
=> Updated dependencies versions

src/phpFastCache/Drivers/Memcache/Driver.php, src/phpFastCache/Drivers/Memcached/Driver.php
(cherry picked from commit eb84c07ff0f1270f704422dd5a16364a4722509b)
=> Fixed notice on Memcache driver when the server just started

.travis.yml, bin/ci/run_tests.php, tests/AbstractProxy.test.php, tests/AttachingDetachingMethods.test.php, tests/NewCacheInstance.test.php, tests/Psr6InterfaceImplements.test.php, tests/SyntaxChecker.test.php
(cherry picked from commit 75bee573f8a79a1165037cd6e4ceb23815b7fae7)
=> Rewrited tests

src/phpFastCache/Util/Directory.php
See https://github.com/PHPSocialNetwork/phpfastcache/pull/384
=> Performance improvement for Directory::getAbsolutePath()

src/phpFastCache/Util/Directory.php
return absolute path on *nix system.
=> #381 Fixed getAbsolutePath

tests/ReadWriteOperations.test.php, tests/issues/Github-373.test.php
- Added IO tests for disk-based drivers
- Real array :)
=> Added IO tests for disk-based drivers + Real array

src/phpFastCache/Drivers/Apcu/Driver.php
And here is the same change for the V6 branch.
=> Apcu driver should not call apc_ functions [V6]

src/phpFastCache/CacheManager.php
=> Simplify CacheManager::validateConfig

src/phpFastCache/Drivers/Memcached/Driver.php
(cherry picked from commit 120234d3271fbd3cdcaf8d112825ac99edc54f4b)
=> Fixed #518

src/phpFastCache/Core/Item/ItemBaseTrait.php, src/phpFastCache/Core/Pool/CacheItemPoolTrait.php, src/phpFastCache/Core/Pool/DriverBaseTrait.php, src/phpFastCache/Core/Pool/ExtendedCacheItemPoolTrait.php, src/phpFastCache/Helper/TestHelper.php, tests/issues/Github-529.test.php
(cherry picked from commit e3d743bdaddd77fc58457eb94b85406d1b84f394)
=> Fixed #529 // Memory leak caused by item tags

docs/CREDITS.md
(cherry picked from commit 055b4c1548c3770ec86d7d898d3fa55c37385126)
=> Adding VersionEye mention to credits

src/phpFastCache/Core/Pool/CacheItemPoolTrait.php
the wiki page seems to have been renamed but the link to it hadn't
=> fixed link to wiki page

.travis.yml, bin/ci/php_phpfastcache.ini, src/phpFastCache/Drivers/Mongodb/Driver.php, tests/Mongodb.test.php
Hi there,
I did a little bit of rework on the MongoDB driver to avoid usage of low level interfaces when not absolutely needed, also I added more checks for the driver, as the ones present originally weren't enough.
Cheers !
=> Cleaned up the Mongodb driver.

.travis.yml, tests/Mongodb.test.php, tests/issues/Github-560.test.php
(cherry picked from commit c1752b831d661b21150ef520d028b35613c6bf01)
=> Fixed randomly failing test Github-#560

README.md
Fixed broken link due to renamed "final" branch
=> Fixed broken link due to renamed "final" branch

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/simple_question.md, .github/PULL_REQUEST_TEMPLATE.md
=> Updated Github bits 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/simple_question.md, composer.json, docs/examples/SaveMultiple.php, docs/examples/cassandra.php, docs/examples/couchbase.php, docs/examples/couchdb.php, docs/examples/files.php, docs/examples/leveldb.php, docs/examples/memcache.php, docs/examples/memcached.php, docs/examples/predis.php, docs/examples/redis.php, docs/examples/riak.php, docs/examples/sqlite.php
- Updated php constraint to be more reliable over the years
- Fixed wrong code in template issues
- Updated examples as per #612 
=> Docs & composer changes

src/phpFastCache/Core/Pool/IO/IOHelperTrait.php, src/phpFastCache/Drivers/Files/Driver.php, src/phpFastCache/Util/Directory.php
=> Preventive hotfix for #614 

CHANGELOG.md
=> Released 6.1.3

CHANGELOG.md, README.md
=>  Released 7.0.1 

docs/migration/MigratingFromV6ToV7.md, lib/Phpfastcache/CacheManager.php, lib/Phpfastcache/Drivers/Apc/Driver.php, lib/Phpfastcache/Drivers/Apcu/Driver.php, lib/Phpfastcache/Drivers/Memcache/Driver.php, lib/Phpfastcache/Drivers/Memcached/Driver.php, lib/Phpfastcache/Drivers/Predis/Driver.php, lib/Phpfastcache/Drivers/Redis/Driver.php, lib/Phpfastcache/Drivers/Wincache/Driver.php
Code mistake in migration guide
=> Fixed #620 

.github/PULL_REQUEST_TEMPLATE.md, docs/migration/MigratingFromV6ToV7.md, lib/Phpfastcache/CacheManager.php, lib/Phpfastcache/Config/ConfigurationOption.php, lib/Phpfastcache/Core/Item/ItemExtendedTrait.php, lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php, lib/Phpfastcache/Core/Pool/DriverBaseTrait.php, lib/Phpfastcache/Core/Pool/ExtendedCacheItemPoolInterface.php, lib/Phpfastcache/Core/Pool/ExtendedCacheItemPoolTrait.php, lib/Phpfastcache/Drivers/Mongodb/Driver.php, lib/Phpfastcache/Drivers/Predis/Driver.php, lib/Phpfastcache/Helper/TestHelper.php, lib/Phpfastcache/Util/MemcacheDriverCollisionDetectorTrait.php
More type hint & opcache optimizations
=> More type hint & opcache optimizations

lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php
Described clear() abstract method
=> Described clear() abstract method

lib/Phpfastcache/Config/ConfigurationOption.php, lib/Phpfastcache/Drivers/Apc/Config.php, lib/Phpfastcache/Drivers/Apcu/Config.php, lib/Phpfastcache/Drivers/Cassandra/Config.php, lib/Phpfastcache/Drivers/Cookie/Config.php, lib/Phpfastcache/Drivers/Couchbase/Config.php, lib/Phpfastcache/Drivers/Couchdb/Config.php, lib/Phpfastcache/Drivers/Devfalse/Config.php, lib/Phpfastcache/Drivers/Devnull/Config.php, lib/Phpfastcache/Drivers/Devtrue/Config.php, lib/Phpfastcache/Drivers/Files/Config.php, lib/Phpfastcache/Drivers/Leveldb/Config.php, lib/Phpfastcache/Drivers/Memcache/Config.php, lib/Phpfastcache/Drivers/Memcached/Config.php, lib/Phpfastcache/Drivers/Memstatic/Config.php, lib/Phpfastcache/Drivers/Mongodb/Config.php, lib/Phpfastcache/Drivers/Predis/Config.php, lib/Phpfastcache/Drivers/Redis/Config.php, lib/Phpfastcache/Drivers/Riak/Config.php, lib/Phpfastcache/Drivers/Sqlite/Config.php, lib/Phpfastcache/Drivers/Ssdb/Config.php, lib/Phpfastcache/Drivers/Wincache/Config.php, lib/Phpfastcache/Drivers/Xcache/Config.php, lib/Phpfastcache/Drivers/Zenddisk/Config.php, lib/Phpfastcache/Drivers/Zendshm/Config.php, lib/Phpfastcache/Event/EventInterface.php, lib/Phpfastcache/Util/ArrayObject.php
Fixed wrong copyright annotation in some file headers
=> Fixed wrong copyright annotation in some file headers

CHANGELOG.md
=> Released 7.0.3

lib/Phpfastcache/CacheManager.php, tests/CacheClearSingleInstance.test.php
Added CacheManager::clearInstance() method
=> Added CacheManager::clearInstance() method

CHANGELOG.md
=> Released 7.0.4 

docs/examples/mongodb.php
Demonstrate usage of Phpfastcache\Drivers\Mongodb\Config in examples
=> Updated Mongodb\Config docs

CHANGELOG.md
=> Released 7.0.5

lib/Phpfastcache/Drivers/Apc/Driver.php
Fixed bug with APC return value on cache clearing
=> Fixed #680

README.md
=>  Fixed typo in readme 

docs/examples/files.php
=> Fixed typo in docs/examples/files.php

lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php
=>  Fixed #694 

CHANGELOG.md
=> Released 6.1.4

.github/stale.yml, CHANGELOG.md, SECURITY.md, lib/Phpfastcache/Drivers/Mongodb/Config.php, lib/Phpfastcache/Drivers/Mongodb/Driver.php, lib/Phpfastcache/Drivers/Predis/Config.php, lib/Phpfastcache/Drivers/Predis/Driver.php
=> Released 7.1.0

lib/Phpfastcache/Drivers/Redis/Driver.php
Removing path check in Redis driver before auth.
=> Removing path check in Redis driver before auth.

CHANGELOG.md
=> Released 7.1.1

.github/workflows/greetings.yml, CHANGELOG.md, README.md, docs/migration/MigratingFromV7ToV8.md
=> Released 8.0.1

lib/Phpfastcache/Drivers/Memcached/Config.php, lib/Phpfastcache/Drivers/Memcached/Driver.php
=> Added Memcached::OPT_PREFIX_KEY option support (fixed #744) 

CHANGELOG.md
=> Released 8.0.2

docs/OPTIONS.md, lib/Phpfastcache/Config/ConfigurationOption.php, lib/Phpfastcache/Core/Item/ItemExtendedTrait.php, lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php, lib/Phpfastcache/Core/Pool/ExtendedCacheItemPoolTrait.php, lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php, tests/DisabledStaticItemCaching.test.php, tests/subprocess/DisabledStaticItemCaching.subprocess.php
=> Added deactivatable static item caching support #754 

lib/Phpfastcache/CacheManager.php, lib/Phpfastcache/Config/ConfigurationOption.php, lib/Phpfastcache/Core/Item/ExtendedCacheItemInterface.php, lib/Phpfastcache/Core/Item/ItemExtendedTrait.php, lib/Phpfastcache/Core/Pool/DriverBaseTrait.php, lib/Phpfastcache/Core/Pool/ExtendedCacheItemPoolInterface.php, lib/Phpfastcache/Drivers/Files/Driver.php, lib/Phpfastcache/Drivers/Sqlite/Driver.php, tests/CustomDefaultFileNameFunction.php, tests/CustomDefaultKeyHashFunction.php
=>  Fixed inconsistent behavior of "defaultKeyHashFunction" and "defaultFileNameHashFunction" + added tests for them

.github/workflows/tests.yml, lib/Phpfastcache/Drivers/Memcached/Driver.php
=> Fixed #758, #759

lib/Phpfastcache/Drivers/Memcached/Driver.php
=>  Fixed #759 

lib/Phpfastcache/Helper/Psr16Adapter.php
=>  Fixed #768 (v8)

lib/Phpfastcache/Helper/Psr16Adapter.php
=>  Fixed #768 (v7)

.travis.yml, CHANGELOG.md
=> Released 8.0.3

.github/workflows/tests.yml, .travis.yml, bin/ci/run_tests.php, lib/Phpfastcache/Drivers/Cookie/Driver.php, lib/Phpfastcache/Drivers/Couchbase/Driver.php, lib/Phpfastcache/Util/ClassNamespaceResolverTrait.php, tests/DriverListResolver.test.php
=> Ensured full PHP8 compatibility

.github/workflows/tests.yml, CHANGELOG.md, lib/Phpfastcache/Api.php, lib/Phpfastcache/CacheManager.php
=> Released 8.0.4 

README.md
=> Added PHP-8 compatibility notice in README

lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php, lib/Phpfastcache/Drivers/Files/Driver.php, lib/Phpfastcache/Drivers/Riak/Driver.php, lib/Phpfastcache/Util/Directory.php
=> Fixed issues in #782 

CHANGELOG.md
=> Released 8.0.5

css/app.css, index.html, js/app.js
- [x ] Improvement (non-breaking change which improves an existing code/behavior)
=> Add Pi Network Mining Referral

lib/Phpfastcache/Helper/CacheConditionalHelper.php
=> Added callback comment for callback argument

.github/workflows/tests.yml
=> Updated tests suite name

CHANGELOG.md, tests/CacheConditional.test.php
=> Released 8.0.6

.gitattributes, docs/examples/phpinfo.php, lib/Phpfastcache/Drivers/Riak/Driver.php
=> [V7] Fixed vulnerability issue that cause exposed phpinfo() in some situations

CHANGELOG.md
=> Released 8.0.7

CHANGELOG.md
=> Released 6.1.5

CHANGELOG.md
=> Released 7.1.2

.travis.yml, bin/ci/install_dependencies.sh, composer.json, lib/Phpfastcache/Drivers/Couchdb/Driver.php, lib/Phpfastcache/Drivers/Mongodb/Config.php, lib/Phpfastcache/Drivers/Mongodb/Driver.php, tests/Mongodb.test.php, tests/lib/Helper/TestHelper.php
=> Updating build + upgrading mongodb & predis dependencies

CHANGELOG.md
=> Released 8.0.8 

.github/workflows/tests.yml, LICENCE, docs/CREDITS.md, docs/EVENTS.md, docs/OPTIONS.md, lib/Phpfastcache/Drivers/Cassandra/Driver.php, lib/Phpfastcache/Drivers/Memstatic/Driver.php, lib/Phpfastcache/Helper/Psr16Adapter.php, tests/Memstatic.test.php
=> Updated some docs files (fixed typos)

lib/Phpfastcache/Helper/Psr16Adapter.php
=> Fixed #831 

lib/Phpfastcache/Drivers/Leveldb/Config.php, lib/Phpfastcache/Drivers/Leveldb/Driver.php
=> Fixed #840

.travis.yml, CHANGELOG.md, lib/Phpfastcache/CacheContract.php, lib/Phpfastcache/Config/ConfigurationOption.php, lib/Phpfastcache/Core/Item/CacheItemTrait.php, lib/Phpfastcache/Drivers/Memcache/Config.php, lib/Phpfastcache/Drivers/Memcache/Driver.php, lib/Phpfastcache/Drivers/Memcached/Config.php, lib/Phpfastcache/Drivers/Memcached/Driver.php, lib/Phpfastcache/Event/EventManagerInterface.php, lib/Phpfastcache/Event/EventReferenceParameter.php, lib/Phpfastcache/EventManager.php, lib/Phpfastcache/Util/Directory.php, tests/CacheContract.test.php, tests/EventManager.test.php, tests/Memcache.test.php, tests/Memcached.test.php, tests/issues/Github-853.test.php, tests/lib/Helper/TestHelper.php
=> Released 9.0.2

bin/ci/scripts/install_couchdb.sh, docs/migration/MigratingFromV4ToV5.md, docs/migration/MigratingFromV5ToV6.md, docs/migration/MigratingFromV6ToV7.md, lib/Phpfastcache/CacheManager.php, lib/Phpfastcache/Core/Pool/ExtendedCacheItemPoolInterface.php, lib/Phpfastcache/Core/Pool/TaggableCacheItemPoolTrait.php, lib/Phpfastcache/Drivers/Couchdb/Driver.php, lib/Phpfastcache/Drivers/Memcache/Driver.php, tests/CoreDriverOverride.test.php, tests/CustomDriver.test.php, tests/DisabledStaticItemCaching.test.php
=> Typo fixes

.github/ISSUE_TEMPLATE/config.yml
=> Added Github issue config file

lib/Phpfastcache/Drivers/Zendshm/Driver.php
Correction of the product link to the Zend Server.
- [ x ] Documentation/Typo/Resource update that does not involve any code modification
=> Update ZendServer product URL
