PHPSocialNetwork/phpfastcache

- phpfastcache/3.0.0/phpfastcache.php
The clause `else if(extension_loaded('pdo_sqlite') && is_writeable($path))` is redundant, because this code path is only executed, if $path is not writeable. So the right part of that and expression is always false and thus the driver will never be set to sqlite.
Additionally #57 claims, that sqlite is a lot slower than files so there is no point in preferring this driver over files by default.
> Removed redundant if clause in getAutoClass()

- README.md
- example2.php
- examples/6.cache_whole_website.php
It's a good idea to always use the identical operator (http://php.net/manual/en/language.operators.comparison.php) when comparing Booleans, so I converted the comparison operators. I ran the codebase through Code Climate (which is how I found the comparison operator instances), so I also added the Code Climate badge to the readme as well.
> Correcting comparisons with Booleans so they use identical operators.

- phpfastcache/3.0.0/phpfastcache.php
Avoid PHP Notices about "undefined index" by checking index existence.
> Avoid Undefined Index Notices

- phpfastcache/3.0.0/drivers/memcache.php
Memcache will only allow a expiration timer less than 2592000 seconds,
otherwise, it will assume you're giving it a UNIX timestamp.
> Fix expiration timer for memcache

- .gitignore
- phpfastcache/3.0.0/abstract.php
- phpfastcache/3.0.0/drivers/files.php
- phpfastcache/3.0.0/drivers/sqlite.php
Recommended to use the “time()”
> Replaced all @date("U") to time()

- phpfastcache/3.0.0/drivers/ssdb.php
- phpfastcache/3.0.0/phpfastcache.php
- phpfastcache/_extensions/SSDB.php
SSDB is a high-performance nosql database, ssdb official website is http://ssdb.io/
> Added new driver : ssdb

- phpfastcache/3.0.0/drivers/predis.php
> Check if Predis is already loaded

- phpfastcache/3.0.0/drivers/files.php
Improved stats function for files driver. Before data property was empty, now it contains array of all keys in cache with each holding array of size and write time.
Also now with PHP 5.3 fix
> Improved stats function for files driver (with PHP 5.3 fix)

- phpfastcache/3.0.0/drivers/files.php
This change will prevent php warnings if the file is not existing anymore.
> add file_exists check for file driver delete function

- phpfastcache/3.0.0/abstract.php
- phpfastcache/3.0.0/drivers/files.php
The file driver currently opens files for writing in a mode which allows other cache readers to read while writes are being performed.
> Modify File Driver to Prevent Partial Reads

- phpfastcache/3.0.0/abstract.php
- phpfastcache/3.0.0/drivers/files.php
- phpfastcache/3.0.0/phpfastcache.php
1. files.php: This updates the previous patch (using flock()) to avoid a race when readers attempt to open the file between the fopen() call and the flock(). 
2. files.php: Now the writer writes the file to $file_path . ".tmp", so no read can occur. Multiple attempts to write will result in the first-writer winning
3. files.php: When writing is complete, the writer pivots (via rename()) the tmp file into the final location (one assumes rename is atomic and instantaneous; I'm sure some FS will prove me wrong)
4. phpfastcache.php: added array_key_exists(<key>,<array) checks to uninitialized access to $config
> Remove race by journaling writes; misc

- phpfastcache/3.0.0/abstract.php
- phpfastcache/3.0.0/drivers/files.php
1. files.php: Switched file_exists() to is_dir() for checks on the intermediate $path
2. files.php: Modified getFilePath() to continue normally if another file-writer creates the directory successfully between calls to is_dir() and mkdir()
3. Reverted abstract.php because locking reads aren't necessary with "journaled" writes.
> Modify "mkdir()" to be multi-writer safe

- phpfastcache/3.0.0/drivers/files.php
- phpfastcache/3.0.0/phpfastcache.php
files.php: fix file writer bug (misplaced paren ) where no file would… write.
phpfastcache.php: fix error where non-www.domain.tld HOST_NAME variables would be stripped of beginning w's in mistaken ltrim call
phpfastcache.php: move filename fixing into static function that removes common "unsafe" characters and positions ("/name?" or "name.")
TODO: call filename fixer in files.php
> Bug Fixes in file writing and dir naming.

- phpfastcache/3.0.0/drivers/redis.php
Fixed the driver class name for Redis.
> Fix the class name for Redis

- .codeclimate.yml
They point out by-design features of phpFastCacche.
> Adjusted codeclimate settings.

- .travis.yml
- src/phpFastCache/Cache/DriverBaseTrait.php
- src/phpFastCache/Core/ExtendedCacheItemPoolTrait.php
- src/phpFastCache/Core/StandardPsr6StructureTrait.php
- src/phpFastCache/Drivers/Files/Driver.php
- src/phpFastCache/Drivers/Sqlite/Driver.php
- tests/AbstractProxy.test.php
- Removed unused datetime check on file-based drivers. They are already handled by the getItem() method
- Fixed bug with tags that leave residues key to tags item themselves
> Multiples fixes

- README.md
- composer.json
- docs/DRIVERS.md
- examples/zend_disk.php
- examples/zend_shm.php
- src/phpFastCache/CacheManager.php
- src/phpFastCache/Drivers/Zenddisk/Driver.php
- src/phpFastCache/Drivers/Zenddisk/Item.php
- src/phpFastCache/Drivers/Zendshm/Driver.php
- src/phpFastCache/Drivers/Zendshm/Item.php
I have added the Zend Data Cache Functions for ZendServer, use new cache functions: zend_shm_cache and zend_diskcache.
See:
http://files.zend.com/help/Zend-Server/content/zendserverapi/zend_data_cache-php_api.htm#function-zend_shm_cache_info
> Add Drivers for Zend Data Cache

- src/phpFastCache/Drivers/Sqlite/Driver.php
This is the same with https://github.com/PHPSocialNetwork/phpfastcache/pull/345.
> Fix the Sqlite driver is unable to fetch expired items

- src/phpFastCache/Util/Directory.php
```php
<?php
$before = microtime(true);
for ($i = 0; $i < 1000000; $i++) {
$win = getAbsolutePath('C:/1/2//3\4/5');
}
$after = microtime(true);
echo ($after - $before) . " sec\n";
var_dump($win);
```
Before PR: 
```
9.4655411243439 sec
string(37) "C:\1\2\3\4\5"
```
After PR: 
```
4.5632607936859 sec
string(37) "C:\1\2\3\4\5"
```
> Performance improvement for Directory::getAbsolutePath()

- src/phpFastCache/Drivers/Apcu/Driver.php
Apcu driver should call apcu_* functions (instead of apc_*) to not be depending on the apcu_bc module.
> Apcu driver should not call apc_ functions

- examples/couchbase.php
'default' => 'Cache' (wrong key 'default', should be 'bucket')
to
'bucket' => 'default'
Took me some time to figure it out, so better change it to more clear example.
> Fix CouchBase driver settings array example

- src/phpFastCache/Drivers/Files/Driver.php
> Clean/delete parent cache directory if it empty after call deleteItem()/deleteItems() for Files driver.

- src/phpFastCache/Drivers/Files/Driver.php
Subj.
I found "issue" when I try to clean all Items by tags (for example),
related files in cache path all removed, but parent dir(s) still leaved also if this dir complete empty.
My simple patch fix this for files driver:
if item file deleted (by @unlink call), also check if parent directory is empty, than also remove this dir too.
> Clean/delete parent cache dirrectory if it empty after call deleteItem()/deleteItems() for Files driver.

- src/phpFastCache/Drivers/Mongodb/Driver.php
A fatal error is triggered by inconsistency through "Driver" class and "DriverBaseTrait" trait. The $instance's access modifiers are different. The bug is fixed dropping $instance field from Driver class. 
On the other hand, removing  `class_exists('MongoDB\Driver\Manager)` from the `Driver::driverCheck` method we can open the posibility to add support for the new mongodb library via an adapter like "alcaeus/mongo-php-adapter"
> Fix mongodb driver

- src/phpFastCache/Helper/Psr16Adapter.php
http://www.php-fig.org/psr/psr-16/
> If a negative or zero TTL is provided, the item MUST be deleted from the cache if it exists, as it is expired already.
> Fix Psr16Adapter caching with negative ttl

- README.md
- composer.json
- src/phpFastCache/Core/Item/ItemBaseTrait.php
- src/phpFastCache/Core/Item/ItemExtendedTrait.php
- src/phpFastCache/Core/Pool/ExtendedCacheItemPoolTrait.php
- Fixed Datetime type hints in ItemExtendedTrait
- Fixed Datetime type hints in ItemBaseTrait
- Updated README to warn users about v7 compatibility
- Added "ext-couchbase" suggestion
> Updated ExtendedCacheItemPoolTrait::deregisterItem() to now only accept string as parameter

- lib/Phpfastcache/Drivers/Mongodb/Config.php
- lib/Phpfastcache/Drivers/Mongodb/Driver.php
The MongoDB Driver, powered by phpfastcache, is designed to function properly when the MongoDB connection is a single server or custom make host string.
You can make your host a string and connect it directly, but you modified it to support it in your library because it could potentially cause developers to make mistakes.
The method of use allows you to add a list of servers to a servers variable, similar to memcached, so that you can add them automatically. 
We can also explicitly add options to the mongodb urI policy, but we did not support it, so we also worked on adding that data.
(https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options)
The changes include :
_Put an `x` in the boxes …
> Support Mongodb Cluster and add uri options.

- lib/Phpfastcache/Drivers/Apcu/Driver.php
The Apcu driver passes `$stats['mem_size']` to the function `setSize()` of `DriverStatistic`. This generates an error due to type mismatch. The function `setSize()` expects and integer while `$stats['mem_size']` is a float.
> fixed bug in Apcu driver.

- lib/Phpfastcache/Core/Pool/DriverBaseTrait.php
- lib/Phpfastcache/Core/Pool/ExtendedCacheItemPoolInterface.php
- lib/Phpfastcache/Exceptions/PhpfastcacheDriverConnectException.php
Added PhpfastcacheDriverConnectException exception in case that a driver failed to connect
> Added PhpfastcacheDriverConnectException exception in case that a driver failed to connect

- lib/Phpfastcache/CacheManager.php
- lib/Phpfastcache/Config/ConfigurationOption.php
- lib/Phpfastcache/Config/IOConfigurationOptionTrait.php
- tests/issues/Github-467.test.php
Moved exclusive files-related configurations keys to IOConfigurationTrait
> Moved exclusive files-related configurations keys to IOConfigurationTrait

- lib/Phpfastcache/Drivers/Mongodb/Config.php
- lib/Phpfastcache/Drivers/Mongodb/Driver.php
Adds the possibility to pass the `$driverOptions`parameter while building the MongoDB Client.
See related issue: https://github.com/PHPSocialNetwork/phpfastcache/issues/663
> Add mongo db driver options

- docs/examples/files.php
I think, those two lines are not needed if the value has already been set and not null.
> I think those lines are not needed

- README.md
Composer 1.8.2 (latest) would now emit a deprecation warning that package name should in lowercase.
So I think it would be better to change the install command in the README.
```
Deprecation warning: require.phpFastCache/phpfastcache is invalid, it should not contain uppercase characters. 
Please use phpfastcache/phpfastcache instead. Make sure you fix this as Composer 2.0 will error.
```
> Fix composer package name should be all lowercase

- README.md
Composer 1.8.2 (latest) would now emit a deprecation warning that package name should in lowercase.
So I think it would be better to change the install command in the README.
```
Deprecation warning: require.phpFastCache/phpfastcache is invalid, it should not contain uppercase characters. 
Please use phpfastcache/phpfastcache instead. Make sure you fix this as Composer 2.0 will error.
```
> [v5] Fix composer package name should be all lowercase

- README.md
Composer 1.8.2 (latest) would now emit a deprecation warning that package name should in lowercase.
So I think it would be better to change the install command in the README.
```
Deprecation warning: require.phpFastCache/phpfastcache is invalid, it should not contain uppercase characters. 
Please use phpfastcache/phpfastcache instead. Make sure you fix this as Composer 2.0 will error.
```
> [v6] Fix composer package name should be all lowercase

- lib/Phpfastcache/Drivers/Couchdb/Driver.php
- lib/Phpfastcache/Drivers/Mongodb/Driver.php
- lib/Phpfastcache/Helper/Psr16Adapter.php
There is an minor bug in the psr16 adapter, the couchdb driver and the mongodb driver.
You throw multiple exceptions with code "NULL". But this will trigger a fatal error in strict mode: https://3v4l.org/fimJH
> Minor bug - fatal error in psr16 adapter if an exception is thrown

- lib/Phpfastcache/Drivers/Ssdb/Driver.php
On this version the server return 0 or 1
In version 1.9.7 of ssdb, it replies with an integer instead of a Bolean generating the following error:
"Return value of Phpfastcache Drivers SSdb Driver :: driverWrite () must be of the type boolean, integer returned"
> ssdb-server 1.9.7

- src/phpFastCache/Helper/Psr16Adapter.php
- tests/Psr16Adapter.test.php
The internal Psr\Cache\CacheItemPoolInterface::deleteItems requires an array as argument. Some popular tools like PhpSpreadsheet use a Traversable instead.
This is the fix for the v6 branch.
deleteMultiple() should convert the `$keys` argument to an array, as the underlying `CacheItemPoolInterface::deleteItems()` method takes arrays only.
This issue also appears in the master branch: I have committed another pull request for the master branch.
> fixes #700 for v6: Psr16Adapter::deleteMultiple converts $keys to an array

- lib/Phpfastcache/Helper/Psr16Adapter.php
- tests/Psr16Adapter.test.php
The internal Psr\Cache\CacheItemPoolInterface::deleteItems requires an array as argument. Some popular tools like PhpSpreadsheet use a Traversable instead.
deleteMultiple() should convert the `$keys` argument to an array, as the underlying `CacheItemPoolInterface::deleteItems()` method takes arrays only.
This issue also appears in the v6 branch: I will commit another pull request to fix it in the 6.x version, too.
> fixes #700: Psr16Adapter::deleteMultiple converts $keys to an array.

- lib/Phpfastcache/Drivers/Cookie/Driver.php
`docs/examples/cookie.php` in `PHP 7.1.25`. An error has occurred the following.
```
Fatal error: Uncaught TypeError: setcookie() expects parameter 2 to be string, integer given in /Users/admin/PhpstormProjects/SampleProject/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Cookie/Driver.php on line 52
TypeError: setcookie() expects parameter 2 to be string, integer given in /Users/admin/PhpstormProjects/SampleProject/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Cookie/Driver.php on line 52
```
I have read the [CONTRIBUTING](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CONTRIBUTING.md) and [CODING …
> Fixed TypeError in lib/Phpfastcache/Drivers/Cookie/Driver.php

- lib/Phpfastcache/Drivers/Redis/Driver.php
Allow `phpfastcache` to attempt to authenticate with Redis if connecting through a UNIX socket. This PR fixes #730 
> Removing superfluous check for unix socket before auth per #730

- lib/Phpfastcache/Config/ConfigurationOption.php
> PHP 7.4 support

- README.md
- lib/Phpfastcache/Core/Pool/TaggableCacheItemPoolTrait.php
`deleteItemsByTags` was calling `deleteItemsByTag` foreach separate tag, ignoring the given strategy
> DeleteItemsByTags was ignoring strategy

- lib/Phpfastcache/Drivers/Redis/Config.php
According to this [example](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/examples/redis.php), password and database options can be nullable. 
```php
$InstanceCache = CacheManager::getInstance('redis', new Config([
'host' => '127.0.0.1', //Default value
'port' => 6379, //Default value
'password' => null, //Default value
'database' => null, //Default value
]));
```
For a given server setup I need these values to be null but, the Config setters didn't accept null values and thrown exception.
I have read the [CONTRIBUTING](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CONTRIBUTING.md) and [CODING GUIDELINE](https://github.com/PHPSocialNetwork/phpfastcache/blo …
> Redis config cannot accept null values as the given example

- lib/Phpfastcache/Helper/CacheConditionalHelper.php
> Allow $cacheItem to be retrieved by callback argument in CacheConditionalHelper

- .gitattributes
- docs/examples/phpinfo.php
> [V8] Fixed vulnerability issue that cause exposed phpinfo() in some situations

- .scrutinizer.yml
- CHANGELOG.md
- lib/Phpfastcache/Core/Item/CacheItemTrait.php
- lib/Phpfastcache/Core/Item/ExtendedCacheItemTrait.php
- lib/Phpfastcache/Core/Item/TaggableCacheItemTrait.php
- lib/Phpfastcache/Core/Pool/DriverBaseTrait.php
- lib/Phpfastcache/Drivers/Apcu/Driver.php
- lib/Phpfastcache/Drivers/Arangodb/Driver.php
- lib/Phpfastcache/Drivers/Cassandra/Driver.php
- lib/Phpfastcache/Drivers/Couchdb/Driver.php
- lib/Phpfastcache/Drivers/Files/Driver.php
- lib/Phpfastcache/Drivers/Memcache/Driver.php
- lib/Phpfastcache/Drivers/Memcached/Driver.php
- lib/Phpfastcache/Drivers/Predis/Driver.php
- lib/Phpfastcache/Drivers/Redis/Driver.php
- lib/Phpfastcache/Drivers/Ssdb/Driver.php
- lib/Phpfastcache/Drivers/Wincache/Driver.php
- lib/Phpfastcache/Drivers/Zenddisk/Driver.php
- lib/Phpfastcache/Drivers/Zendshm/Driver.php
- tests/Memcached.test.php
- tests/issues/Github-860.test.php
- tests/lib/Helper/TestHelper.php
> Released 9.1.1

- README.md
- docs/DRIVERS.md
> Prepared readme to announce Relay implementation

- .github/workflows/testsv2.yml
- lib/Phpfastcache/Drivers/Redis/Driver.php
- lib/Phpfastcache/Drivers/Rediscluster/Driver.php
The Redis driver's function to read all keys has been streamlined. The change is adding a loop to scan and merge the keys iteratively. This ensures that the function will work correctly, even when the number of keys scanned exceeds the MAX_ALL_KEYS_COUNT.
This is a fix for https://github.com/PHPSocialNetwork/phpfastcache/issues/912
> Refactor Redis driver to read all keys efficiently

- lib/Phpfastcache/CacheContract.php
- lib/Phpfastcache/Cluster/AggregatorInterface.php
- lib/Phpfastcache/Cluster/ClusterAggregator.php
- lib/Phpfastcache/Drivers/Redis/Config.php
- lib/Phpfastcache/Exceptions/PhpfastcacheCorruptedDataException.php
- lib/Phpfastcache/Exceptions/PhpfastcacheIOException.php
- lib/Phpfastcache/Helper/Psr16Adapter.php
This PR fixes the PHP 8.4 deprecation warnings related to implicitly nullable parameters. In PHP 8.4, parameters with a default value of null must be explicitly marked as nullable using the '?' prefix.
Fixes #924 and #926
Changes:
1. Fixed Redis Config::setDatabase() method (issue #924)
2. Fixed PhpfastcacheIOException constructor (issue #926)
3. Fixed additional similar occurrences in:
- PhpfastcacheCorruptedDataException constructor
- Psr16Adapter constructor
- ClusterAggregator::aggregateDriverByName
- AggregatorInterface::aggregateDriverByName
- CacheContract::get and __invoke methods
These changes ensure compatibility with PHP 8.4 while maintaining backward compatibility with PHP 8.0+.
_Put an `x` in the boxes that …
> Fix PHP 8.4 deprecation warnings for implicitly nullable parameters
